name: Actions Workflow

on:
  # schedule:
  #   - cron:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
  
  push:
    branches:
      - main    
     # - 'feature/*'
     # - '!feature/testC'
    # branches-ignore:
    #   - ""  
    # tags:
    #   - ""
    # tags-ignore:
    #   - ""
    # paths:
    #   - 
    # paths-ignore:
    #   - ""     

  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:     
      - name: List Files Before Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: payload
        run: echo "${{github.event.cilent_payload.env}}"    
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
