name: Shell commands

on:  
  workflow_dispatch:  
  push:
    branches:
      - main    
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print('Platform processor:', platform.processor())
          print('Platform architecture:', platform.architecture())
          print('Machine type:', platform.machine())
          print('Systems network name:', platform.node())
          print('Platform information:', platform.platform())
          print('Operating system:', platform.system())
          print('System info:', platform.system())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs:
      - run-shell-commands
    steps:
      - name: Directory Windows
        run: Get-location
      - name: Directory Bash
        run: pwd
        shell: bash
