name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print('Platform processor:', platform.processor())
          print('Platform architecture:', platform.architecture())
          print('Machine type:', platform.machine())
          print('System's network name:', platform.node())
          print('Platform information:', platform.platform())
          print('Operating system:', platform.system())
          print('System info:', platform.system())
        shell: python
