name: wf-one

on: [push]

jobs: 
  call-wf-two:
    uses: vamsea2002/git-hub-actions-test/.github/workflows/wf-two.yml@main
    with:
      username: vamsi
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV          
          echo $GIT_BRANCH
          echo ${{ github.head_ref }}
        
