name: wf-one

on: [push]

jobs: 
  call-wf-two:
    uses: vamsea2002/git-hub-actions-test/.github/workflows/wf-two.yml@main
    with:
      username: vamsi
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: vamsea2002/hello-world-composite-action@v1
      
        
