name: wf-two

on:
  workflow_call:
   inputs:
     username:
      required: true
      type: string

jobs: 
  create_issue:
    runs-on: ubuntu-latest 
    
    steps:
      - name: echo info
        run: |  
          echo "from wf-two"
          echo ${{inputs.username}}
